# Site settings
title: Lotus Moon's Blog
SEOTitle: 荷边赏月的博客 | Lotus Moon's Blog
header-img: img/home-bg-3.jpg
email: lotus_0_moon@sina.com
description: '这里是 @荷边赏月 的个人博客，与你一起发现更大的世界 | 要做一个有梦想的人'
keyword: '荷边赏月, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计'
url: 'https://lotus-moon-0.github.io' # your host, for absolute URL
baseurl: '' # for example, '/blog' if your blog hosted on 'host/blog'


# Publish posts or collection documents with a future date.
future: true


# SNS settings
RSS: false
# weibo_username: N/A
# zhihu_username: N/A
github_username: Lotus-Moon-0
# twitter_username: N/A
# facebook_username:  N/A
# linkedin_username:  firstname-lastname-idxxxx


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    'less',
    'node_modules',
    'Gruntfile.js',
    'package.json',
    'README.md',
    'README.zh.md',
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jekyll-sitemap]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Comments settings
comments: true
# Gitalk settings
# 发完 Blog，自己先打开一下，初始化 Gitalk
gitalk:
  enable: true
  clientID: 89dd26d4cc9cc7d512f9
  clientSecret: 0561201d77372bd5cb5e65de63b0573838153e5f
  repo: Lotus-Moon-0.github.io
  owner: Lotus-Moon-0
  admin: ['Lotus-Moon-0', 'DLM-BFC-DLM']
  proxy: https://cors-server-ecru.vercel.app/github_access_token

# Netease settings
netease:
  enable: false

# Disqus settings
disqus:
  enable: false
  # disqus.username: dcjin


# Analytics settings
# Baidu Analytics
ba_track_id: dd9761aaf8166618d79b999ab965fd10

# Google Analytics
# ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me


# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: '心有猛虎，细嗅蔷薇。'
sidebar-avatar: /img/avatar-LM.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: '#000000'
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Friends
# friends:
#   [
#     { title: "乱序（Midare）", href: "http://mida.re/" },
#     { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#     { title: "Kun Qian", href: "http://kunq.me" },
#     { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#     { title: "SmdCn", href: "http://blog.smdcn.net" },
#     { title: "JiyinYiyong", href: "http://tiye.me/" },
#     { title: "DHong Say", href: "http://dhong.co" },
#     { title: "尹峰以为", href: "http://ingf.github.io/" },
#   ]


# Theme
# theme: merlot
# remote_theme: merlot
