on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push urls
        uses: 3Alan/search-engines-urls-push@v0.2.3
        with:
          site: ${{ secrets.SITE }}
          sitemap: ${{ secrets.UPDATEDURLS }}
          bing-token: ${{ secrets.BING_TOKEN }}
