name: Send urls to Bing
on:
  push:
    branches:
      - main

jobs:
  Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sleep for 2 minutes
        run: sleep 120s
        shell: bash
